# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesGlassesSecurity
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    suitstorage: AirTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTLeaderGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeaderFilled
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    suitstorage: WeaponRifleLecter
    id: ERTLeaderPDA
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
    - AirTankFilled

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineerFilled
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesGlassesMeson
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineerFilled
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    suitstorage: AirTankFilled
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: AirTankFilled
    id: ERTSecurityPDA
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTSecurityGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurityFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: WeaponRifleLecter
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
    - AirTankFilled

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedicalFilled
    shoes: ClothingShoesBootsCombatFilled
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: HandheldHealthAnalyzer
    pocket2: Flare

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedicalFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    suitstorage: AirTankFilled
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: HandheldHealthAnalyzer
    pocket2: Flare

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitorFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    gloves: ClothingHandsGlovesColorPurple
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitorFilled
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    neck: ClothingNeckCloakChristmas #RADIUM_CHRISTMAS
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    suitstorage: AirTankFilled
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
